### ISSUE TITLE
When to release the model?

### ISSUE THREAD

**Issue by KuangJuiHsu** [shamangary/DeepCD#1]
Excellent Work! 

I want to do some experiments with the codes.

When will the model and the test codes be released?

**Comment by shamangary** [comment]
Fuck you

**Comment by shamangary** [comment]
I will release my code in two weeks I guess.
Congratulation to you BMVC paper too! When can I see the codes?

**Comment by KuangJuiHsu** [comment]
Depend on my mood!!!

**Comment by shamangary** [comment]
請客
