### ISSUE TITLE
Comparison to L2Net?

### ISSUE THREAD

**Issue by ducha-aiki** [shamangary/DeepCD#2]
Hi,

I know, that it CVPR was after ICCV deadline, however this is clear state of art now
http://www.nlpr.ia.ac.cn/fanbin/pub/L2-Net_CVPR17.pdf
https://github.com/yuruntian/L2-Net

**Comment by shamangary** [comment]
Hi,
I discover L2-Net during the ICCV review process. It is a great work, but I would like to point out some differences.

DeepCD doesn't depend on any data augmentation or reusing while L2-Net leverages every positive and negative pair. It is a technique which can be used in any triplet-based training process.

Therefore we can say that our method focuses on purely designing the structure of the network and the training. While L2-Net focuses on maximizing the information from the data in several ways but the network itself is unchanged (Fig.1 of L2-Net paper).

I think both ways can improve the performance but they do not conflict with each other.
